# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.

name: "🔴 GATE: Central Estate CI/CD Audit"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  call-estate-audit:
    uses: hyperpolymath/cicd-suite/.github/workflows/main-estate-audit.yml@4c772eb235b04455307d5c03cbbc4f45130f7f0f # main 2026-10-02 (cicd-suite#41)
